from typing import Dict, List

class PyVariable:
    name: str
    min: float
    max: float
    def __init__(self, name: str, min: float, max: float) -> None: ...
    def add_triangle(self, term_name: str, a: float, b: float, c: float) -> None:
        """Adds a triangular membership function to the variable"""
        ...
    def add_trapezoid(
        self, term_name: str, a: float, b: float, c: float, d: float
    ) -> None: 
        """Adds a trapezoidal membership function to the variable"""
        ...
    def fuzzify(self, x: float) -> Dict[str, float]:
        """Fuzzifies a crisp value x and returns a dictionary mapping term names to their membership values"""
        ...
    def plot(self) -> None:
        """Plots the membership functions of the variable"""
        ...

class PyAntecedent:
    def __init__(self, variable: str, term: str) -> None: ...
    def __invert__(self) -> "PyAntecedent": ...
    def __and__(self, other: "PyAntecedent") -> "PyAntecedent": ...
    def __or__(self, other: "PyAntecedent") -> "PyAntecedent": ...

class PyRule:
    def __init__(
        self, antecedent: PyAntecedent, consequent_var: str, consequent_term: str
    ) -> None: ...
    def evaluate(self, state: Dict[str, Dict[str, float]]) -> float:
        """Evaluates the rule given a state, which is a dictionary mapping variable names to their fuzzified values (which are dictionaries mapping term names to membership values)"""
        ...

class PyFuzzyEngine:
    def __init__(self) -> None: ...
    def add_input(self, variable: PyVariable) -> None:
        """Adds an input variable to the fuzzy engine"""
        ...
    def add_output(self, variable: PyVariable) -> None:
        """Adds an output variable to the fuzzy engine"""
        ...
    def add_rule(self, rule: PyRule) -> None:
        """Adds a rule to the fuzzy engine"""
        ...
    def compute(self, inputs: Dict[str, float]) -> Dict[str, float]:
        """Computes the output of the fuzzy engine given a set of inputs"""
        ...
    def input_names(self) -> List[str]:
        """Returns a list of the names of the input variables"""
        ...
    def inputs(self) -> List[PyVariable]:
        """Returns a list of the input variables"""
        ...
    def get_input(self, name: str) -> PyVariable | None:
        """Returns the input variable with the given name, or None if it does not exist"""
        ...
    def output_names(self) -> List[str]:
        """Returns a list of the names of the output variables"""
        ...
    def outputs(self) -> List[PyVariable]:
        """Returns a list of the output variables"""
        ...
    def get_output(self, name: str) -> PyVariable | None:
        """Returns the output variable with the given name, or None if it does not exist"""
        ...
    def variable_names(self) -> List[str]:
        """Returns a list of the names of all variables (both inputs and outputs)"""
        ...
    def variables(self) -> List[PyVariable]:
        """Returns a list of all variables (both inputs and outputs)"""
        ...
    def get_variable(self, name: str) -> PyVariable | None:
        """Returns the variable with the given name, or None if it does not exist"""
        ...
    def rules(self) -> List[PyRule]:
        """Returns a list of all rules in the fuzzy engine"""
        ...
    def plot_decision_surface(self, input1: str, input2: str, output: str) -> None: 
        """Plots the decision surface of the fuzzy engine for the given input and output variables"""
        ...
