from typing import Dict, List

class PyVariable:
    name: str
    min: float
    max: float
    def __init__(self, name: str, min: float, max: float) -> None: ...
    def add_triangle(self, term_name: str, a: float, b: float, c: float) -> None: ...
    def add_trapezoid(
        self, term_name: str, a: float, b: float, c: float, d: float
    ) -> None: ...
    def fuzzify(self, x: float) -> Dict[str, float]: ...
    def plot(self) -> None: ...

class PyAntecedent:
    def __init__(self, variable: str, term: str) -> None: ...
    def __invert__(self) -> "PyAntecedent": ...
    def __and__(self, other: "PyAntecedent") -> "PyAntecedent": ...
    def __or__(self, other: "PyAntecedent") -> "PyAntecedent": ...

class PyRule:
    def __init__(
        self, antecedent: PyAntecedent, consequent_var: str, consequent_term: str
    ) -> None: ...
    def evaluate(self, state: Dict[str, Dict[str, float]]) -> float: ...

class PyFuzzyEngine:
    def __init__(self) -> None: ...
    def add_input(self, variable: PyVariable) -> None: ...
    def add_output(self, variable: PyVariable) -> None: ...
    def add_rule(self, rule: PyRule) -> None: ...
    def compute(self, inputs: Dict[str, float]) -> Dict[str, float]: ...
    def input_names(self) -> List[str]: ...
    def inputs(self) -> List[PyVariable]: ...
    def get_input(self, name: str) -> PyVariable | None: ...
    def output_names(self) -> List[str]: ...
    def outputs(self) -> List[PyVariable]: ...
    def get_output(self, name: str) -> PyVariable | None: ...
    def variable_names(self) -> List[str]: ...
    def variables(self) -> List[PyVariable]: ...
    def get_variable(self, name: str) -> PyVariable | None: ...
    def rules(self) -> List[PyRule]: ...
    def plot_decision_surface(self, input1: str, input2: str, output: str) -> None: ...
